FROM python:3.12
RUN pip install fastapi uvicorn

ARG FRONTEND_URL_CROSS="kind-glacier-033cd360f.5.azurestaticapps.net"
ENV FRONTEND_URL_CROSS=$FRONTEND_URL_CROSS

COPY ./ /app
WORKDIR /app

EXPOSE 8000

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]