name: release pipeline

on:
  push:
    branches:
      - 'master'

jobs:
  create-artfact-backend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build ./backend -t matheuskimura/backend-fastapi:latest
  
  publish-artfact-backend:
    needs: create-artfact-backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Publish Docker image
        uses: azure/docker-login@v1
        with:
          login-server: inspiradevops.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
      - run: |
          docker build ./backend -t inspiradevops.azurecr.io/mcookie:latest
          docker push inspiradevops.azurecr.io/mcookie:latest

  create-artfact-frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: npm ci
      - name: Building application
        run: npm run build
      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: react-frontend
          path: ./frontend/build
                
      