name: Build, Publish and Deploy (Azure)

on:
  push:
    branches:
      - 'master'

jobs:
  create-publish-artfact-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Publish Docker image
        uses: azure/docker-login@v1
        with:
          login-server: inspiradevops.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
      - run: |
          docker build ./backend -t inspiradevops.azurecr.io/mcookie/backend-fastapi:${{ github.sha }}
          docker push inspiradevops.azurecr.io/mcookie/backend-fastapi:${{ github.sha }}
  
  deploy-backend:
    runs-on: 'ubuntu-latest'
    needs: create-publish-artfact-backend
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://inspiradevops.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_14f2a04e620e4de5806bf69190d83213 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_bc7d3c944a9c40f2bc108af35273a106 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Calculator-Backend-Devops'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_39dc3899d8bd42f4a53c239f89f5d6b3 }}
          images: 'inspiradevops.azurecr.io/mcookie-backend-fastapi:${{ github.sha }}'

  create-publish-artfact-frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: npm ci
      - name: Building application
        run: npm run build
      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: react-frontend
          path: ./frontend/build

  deploy-artfact-frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    needs: create-publish-artfact-backend
    
    steps:
      - uses: actions/checkout@v2

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: npm ci

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: react-frontend
      
      - name: Test artifact
        run: ls -R
        