# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Calculator-Backend-Devops

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://inspiradevops.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_14f2a04e620e4de5806bf69190d83213 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bc7d3c944a9c40f2bc108af35273a106 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: inspiradevops.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_14f2a04e620e4de5806bf69190d83213 }}/mcookie/backend-fastapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Calculator-Backend-Devops'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_39dc3899d8bd42f4a53c239f89f5d6b3 }}
        images: 'inspiradevops.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_14f2a04e620e4de5806bf69190d83213 }}/mcookie/backend-fastapi:${{ github.sha }}'