name: release pipeline

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-artfact-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build ./backend -t matheuskimura/backend-fastapi:latest

      - name: Publish Docker image
        run: |
          docker login -u matheuskimura -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push matheuskimura/backend-fastapi:latest

  build-artfact-frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: npm ci
      - run: npm run build

      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
     
      - run: npm pack

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: react-frontend
          path: ./frontend/*.tgz
                
      