name: release pipeline

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-artfact-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build ./backend -t matheuskimura/backend-fastapi:latest

      - name: Publish Docker image
        run: |
          docker login -u matheuskimura -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push matheuskimura/backend-fastapi:latest

  create-artfact-frontend:
    runs-on: ubuntu-latest
            
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20.8.1"
          registry:-url: https://https://npm.pgk.github.com/
          scope: https://npm.pgk.github.com

      - name: Install package
        working-directory: ./frontend
        run: npm install

      - name: Publish package
        working-directory: ./frontend
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_GITHUB_TOKEN }}
      