name: run tests

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test-backend:
    runs-on: ubunto-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Nodev set up
        uses: actions/setup-python@v4
      - run: npm ci
          